### ISSUE TITLE
jQuery - Best Practice within components?

### ISSUE THREAD

**Issue by simplethemes** [misterGF/CoPilot#22]
The AdminLTE theme makes heavy use of jQuery.

It'd be nice to have access to `$` and maybe even the included plugins (select2(), etc) within the global space. Do you have a preference or opinion on how to register each without including twice?

**Comment by simplethemes** [comment]
I got around the eslint error by adding this to .eslintrc.js, however the plugin functions are squawking because they aren't defined. If I import select2 within a component, does that mean it's included in the package twice?

```
  'env': {
    'browser': true,
    'commonjs': true,
    'es6': true,
    'jquery': true
  }
```

**Comment by xeoshow** [comment]
Mark and also would like to know the answer...

**Comment by euvl** [comment]
The whole idea if using Vue for admin lte is to divide project into components with their own dependencies and cut the usage of global stuff i think, otherwise what's the point of using the framework that does it..  

Ideally for your components that require jquery you will do:
```
import $ from 'jquery'
```

Alternatively, if you do not want to include it in every component, you can always use:
``` 
window.$
```

Or you can bind it to Vue prototype in your `main.js` file:
```
import jquery from 'jquery'
Vue.prototype.$ = jquery
```
and use it like:
```
...
methods: {
  foo () {
    this.$.dosomething()
  }
}
 ```
