### ISSUE TITLE
Selecting an item from the navbar and then hitting F5/refresh gives page not found

### ISSUE THREAD

**Issue by gabn88** [misterGF/CoPilot#33]
When I select an item from the navbar and then hit F5, I got page not found.

I suggest to either 1. use hash-tag urls (#dashboard instead of /dashboard), 2. put a notification inside the readme that a backend has to be written that mimics the urls/entry points.

**Comment by misterGF** [comment]
Thanks @gabn88.

I recommend option 2 to keep URLs clean. However, it is easy enough to change if you prefer option 1.

The server that runs off of **npm run dev** is configured always respond with the / url and vue-router takes care of the rest. No need to mimic.

The issue you see in the demo is due to the provider. I need to make a few changes to get it to also respond with the / regardless of the URL specified. Will look into fixing it soon.

**Comment by misterGF** [comment]
Latest commit fixes this.

033a5a09c48f548acc4e5d27c35906bc758204df

**Comment by gabn88** [comment]
Quick fix! 🥇 

Just one more thing: if another navbar item is selected, the selection jumps back to dashboard after an F5.

**Comment by misterGF** [comment]
Hmm...Which browser are you using? I'm not experiencing that.

**Comment by gabn88** [comment]
Latest chrome.

Click for example tables, then refresh the page. You will still see the tables view, but on the navbar the dashboard is selected. Not a biggie, but more nice to have ☺

**Comment by misterGF** [comment]
I understand now. It will take some code added [here ](https://github.com/misterGF/CoPilot/blob/master/src/components/SidebarMenu.vue)to get it to work.

It should probably evaluate the Vue.$route.name to determine where it is and it can then find the proper li to add the active class too.

Want to take a stab at it?
