### ISSUE TITLE
adding support for morris.js

### ISSUE THREAD

**Issue by opensas** [misterGF/CoPilot#79]
I'm trying to add support or Morris.js graphics, so I issue `npm install --save morris.js`, but when I run `npm run dev` I keep getting this error:

    ERROR  Failed to compile with 1 errors
    This dependency was not found:
    * morris.js in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/views/Dashboard.vue
    To install it, you can run: npm install --save morris.js

Am I missing something???

BTW, asked the same (with more details) on [SO](https://stackoverflow.com/questions/55015058/vue-dependency-not-found-after-running-npm-install-save)

(I'm giving my first steps with vue, please forgive me if this is a newbvie question ;-))

**Comment by misterGF** [comment]
I'm not too familiar with morris but from what I can tell it doesn't have support for loading a module using import. It's been a while since the library has been updated.

You can try to import it via a require (const morris = require('morris.js') but I'd suggest looking for an active project that has what you are looking for.
